# Generated by Django 3.2.4 on 2021-06-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieID', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('genres', models.CharField(max_length=30)),
                ('rate', models.FloatField()),
                ('votes', models.IntegerField()),
            ],
        ),
    ]
